# Generated by Django 5.0.3 on 2024-03-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_app", "0003_delete_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
