# Generated by Django 5.0.3 on 2024-03-09 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_app", "0007_attendance_break_workday"),
    ]

    operations = [
        migrations.AddField(
            model_name="workday",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
