# Generated by Django 5.0.3 on 2024-03-09 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_app", "0008_workday_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="user",
        ),
        migrations.RemoveField(
            model_name="break",
            name="attendance",
        ),
        migrations.RemoveField(
            model_name="workday",
            name="attendance",
        ),
        migrations.RemoveField(
            model_name="workday",
            name="break_end_time",
        ),
        migrations.RemoveField(
            model_name="workday",
            name="break_start_time",
        ),
        migrations.AddField(
            model_name="attendance",
            name="workday",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance",
                to="attendance_app.workday",
            ),
        ),
        migrations.AddField(
            model_name="break",
            name="workday",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance_app.workday",
            ),
        ),
        migrations.AlterField(
            model_name="workday",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
